services:
  api:
    build: .
    restart: always
    # ports:
    # - "8000:8000"
    environment:
      - PORT=8000 
    depends_on:
      nginx:
        condition: service_started
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificates:/etc/nginx/certificates

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  # redis-stack:
  #   image: redis/redis-stack-server:latest
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_ARGS=--requirepass redis_password
  #   volumes:
  #     - redis_data:/data
  #   restart: always

volumes:
  postgres_data:
  # redis_data:
