services:
  api:
    build: .
    # ports:
    #   - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificates:/etc/nginx/certificates
